Option Explicit

Dim Snd
Set Snd = CreateObject("WMPlayer.OCX")
Dim sns
Set sns = WScript.CreateObject("WScript.Shell")
Dim strText
Dim strTitle
Dim intResult
dim intType

If WScript.Arguments.Count <> 0 then
    Select Case WScript.Arguments(0)
    Case "/StrtpSnd": Startup
    Case "/Test": Window1
    Case "/WinIsEOL_Partial": Window2
    Case "/WinIsEOL": Window3
    Case "/OldWinX": Window4
    Case "/SnsUiCooldown": UiCooldown
    Case "/SnsUiCd": UiBigCd
    Case "/EOS_Arch": Window5
    Case "/Critical": UiCrash
    End Select
end if

Set Snd = Nothing

Sub Startup()
    Snd.URL = "C:\Windows\Media\Windows Logon.wav"
    Snd.controls.play 
    While Snd.playState <> 1 
      WScript.Sleep 100
    Wend
    
    Snd.close
End Sub

Sub Window1()
    MsgBox "SNS-DOS is testing messages",0,"SNS-DOS Notify System"
End Sub

Sub Window2()
    MsgBox "SNS-DOS is partially supported by Windows Vista with Extended Kernel / Windows 7 SP1 / 8.x, but you may need a patch to be able to update SNS-DOS.",64,"SNS-DOS Compatibility"
End Sub

Sub Window3()
    MsgBox "SNS-DOS isn't supported in Windows 7 SP0 / Windows Vista SP0-SP1 / Windows XP or earlier. You can still use SNS-DOS, but we don't guarantee that SNS-DOS will work stably. We recommend upgrading Windows to Windows Vista or install Service Pack.",16,"SNS-DOS Compatibility"
End Sub

Sub Window4()
    MsgBox "This Windows 10 version is supported (LTSB or LTSC), but we still recommend upgrading to the latest version (20H1 and later). You can still use SNS-DOS, but the patch is still needed.",48,"SNS-DOS Compatibility"
End Sub

Sub Window5()
    MsgBox "SNS-DOS isn't supported by x32 CPUs. SNS-DOS recommends installing x64 version on Windows or switching to x64 PC.",16,"SnsUI Error"
End Sub

Sub UiCooldown()
    WScript.Sleep 400
End Sub

Sub UiBigCd()
    WScript.Sleep 2000
End Sub

Sub UiCrash()
    strText = "SNS-DOS is crashed." & Chr(13)
    strText = strText & "Do you want to restart SNS-DOS anyways?"
    strTitle = "SNS-DOS is crashed ;("
    intType = vbYesNo + vbCritical
    intResult = sns.Popup(strText, ,strTitle, intType)
    Select Case intResult
        Case vbYes
            sns.Run "sns_en.cmd /Native", 1, False
        Case vbNo
            WScript.Sleep 100
    End Select
End Sub

Sub UiUpdateAvailable()
    strText = "SnsUpdate has found new SNS-DOS update." & Chr(13)
    strText = strText & "Do you want to manually install new SNS-DOS update?"
    strTitle = "SnsUpdate"
    intType = vbYesNo + vbQuestion
    intResult = sns.Popup(strText, ,strTitle, intType)
    Select Case intResult
        Case vbYes
            sns.Run "snsupdate.cmd /UpgradePage", 1, False
        Case vbNo
            WScript.Sleep 100
    End Select
End Sub

' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)
' Used to fill VBS file (to stabilise size increases)